{% set python_min = "3.11" %}
{% set name = "zarr" %}
{% set version = "3.0.10" %}
{% set sha256 = "1fd1318ade646f692d8f604be0e0ad125675a061196e612e3f7a2cfa9e957d1c" %}

package:
  name: zarr
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/z/zarr/zarr-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - packaging >=22.0
    - numpy >=1.25
    - numcodecs >=0.14
    - typing_extensions >=4.9
    - donfig >=0.8
    - crc32c
  run_constrained:
    - fsspec >=2023.10.0

test:
  requires:
    - pip
    - python {{ python_min }}
    - pytest
    - pytest-asyncio
    - hypothesis
    - botocore
    - fsspec
    - requests
    - aiohttp
    - rich
    - universal_pathlib
  source_files:
    - tests
    - pyproject.toml
  imports:
    - zarr
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/zarr-developers/zarr-python
  license: MIT
  license_file: LICENSE.txt
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  doc_url: https://zarr.readthedocs.io/

extra:
  recipe-maintainers:
    - normanrz
    - martindurant
    - d-v-b
    - jakirkham
    - joshmoore
    - jhamman
    - rabernat
    - dstansby
