{% set python_min = "3.11" %}
{% set name = "zarr" %}
{% set version = "2.18.6" %}
{% set sha256 = "2e4a6ad1b2ff57b652beba5a3a653b49da774514b28d224d84c5cd8ee72641af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >8
  run:
    - python >={{ python_min }}
    - asciitree
    - numpy >=1.24
    - fasteners
    - numcodecs >=0.10.0,!=0.14.0,!=0.14.1,<0.16.0a0
  run_constrained:
    # Add `zarr[jupyter]` dependencies to `run_constrained`.
    # That way the correct versions of these will be installed
    # when these packages are requested. Otherwise they are not
    # installed.
    - notebook
    - ipytree >=0.2.2
    - ipywidgets >=8.0.0

test:
  requires:
    - pip
    - pytest
    # Needs `packaging` in the tests
    # xref: https://github.com/zarr-developers/zarr-python/pull/1450
    - packaging
    - python {{ python_min }}
  imports:
    - zarr
  commands:
    - pip check
    - pytest -v --pyargs zarr

about:
  home: https://github.com/zarr-developers/zarr-python
  license: MIT
  license_file: LICENSE.txt
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  doc_url: https://zarr.readthedocs.io/

extra:
  recipe-maintainers:
    - normanrz
    - martindurant
    - d-v-b
    - jakirkham
    - joshmoore
    - jhamman
    - rabernat
    - dstansby
