travis:
  secure:
    BINSTAR_TOKEN: g+4QUvpzfB3GOZJSbt4pb2kicDnu9v4EJzbo9MG660cx0SQPU+ctb6GUBKhUGrhjddyeNay9ZfitZdfmZIXuBbE+lI+auyPFx2Tl8VjCqSBdyfio8CURWRlF5Ilt5ynjGdm73dmaGc+KTvChTnjwijCgIGRFAeR1e/zMYI1Qhg/Psy/UCxf1/PobSEsbmsZgxFeRUCFfHFwhPjifPetrHH0uuQ9HWrvMK2m9aPhH5ZihyH7JxN+9d5ul5Yk0sqIvk5jG8ltp8aXqE1XuVaWnQ3ujit/ClGX8ptZx/gBNcDxmtmk33THKEkj5LZv9MHC9ur+dhpffioOukzWzuGTrvOdZdlQ4Tk1f6VcqujlxnURkgaBqX158KD5F+flN3kB44f3AdJR1n7as3S+JjFxkpjO7RXMxyT5HBjzxweGc21oM2DtRG2cockMTJfqv7C8C0C7mg9P7wB9BLl2sLe3MClg/VqGhT6DKF+U6pigIO39cKs4BVXjWqPpqc4v0mdILAx9PizNNQdQLV3ey05nlNuiTPmIKlZbg4pqv0gUASmG/FhVJbgfZLAbbbl+Z3zI/s8OYXKpYP8Mh1xlO11n7mgW5qI0yNE/q+pflB4kSQkL5iaVBCYNxYkYOUEOQn6PviT9LuZhG9Mw2724dwLjS2+t5yxuesMumBKOuecP3zHc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
  targets:
    - [conda-forge, rc]
